// Generated by gencpp from file dynamixel_sdk_examples/SetPosition.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_SDK_EXAMPLES_MESSAGE_SETPOSITION_H
#define DYNAMIXEL_SDK_EXAMPLES_MESSAGE_SETPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamixel_sdk_examples
{
template <class ContainerAllocator>
struct SetPosition_
{
  typedef SetPosition_<ContainerAllocator> Type;

  SetPosition_()
    : id(0)
    , id2(0)
    , position(0)
    , position2(0)  {
    }
  SetPosition_(const ContainerAllocator& _alloc)
    : id(0)
    , id2(0)
    , position(0)
    , position2(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _id2_type;
  _id2_type id2;

   typedef int32_t _position_type;
  _position_type position;

   typedef int32_t _position2_type;
  _position2_type position2;





  typedef boost::shared_ptr< ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator> const> ConstPtr;

}; // struct SetPosition_

typedef ::dynamixel_sdk_examples::SetPosition_<std::allocator<void> > SetPosition;

typedef boost::shared_ptr< ::dynamixel_sdk_examples::SetPosition > SetPositionPtr;
typedef boost::shared_ptr< ::dynamixel_sdk_examples::SetPosition const> SetPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator1> & lhs, const ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.id2 == rhs.id2 &&
    lhs.position == rhs.position &&
    lhs.position2 == rhs.position2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator1> & lhs, const ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamixel_sdk_examples

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "086f23b0353cf484b4bd30c53e073691";
  }

  static const char* value(const ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x086f23b0353cf484ULL;
  static const uint64_t static_value2 = 0xb4bd30c53e073691ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_sdk_examples/SetPosition";
  }

  static const char* value(const ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"uint8 id2\n"
"int32 position\n"
"int32 position2\n"
;
  }

  static const char* value(const ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.id2);
      stream.next(m.position);
      stream.next(m.position2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_sdk_examples::SetPosition_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "id2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id2);
    s << indent << "position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position);
    s << indent << "position2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_SDK_EXAMPLES_MESSAGE_SETPOSITION_H
